import type { BusinessProfile } from "./types";

export const businessProfiles: BusinessProfile[] = [
  {
    id: "default",
    name: "Default",
    industry: "General business",
    businessType: "General operations",
    context: "Default communication review profile for general messages.",
    description: "Generic business profile for broad communication analysis.",
    departments: ["Executive", "Operations", "Finance", "Customer Support"],
    productsOrServices: ["General services"],
    supportTone: "Professional",
    communicationStyle: "Clear and concise",
    riskTolerance: "Medium",
    priorityRules: ["Escalate legal, security, payment and customer-impacting issues."],
    escalationRoles: ["Operations Lead", "Finance Team"],
    officialDomains: [],
    trustedLinks: [],
    policyNotes: "Use supplied evidence only. Do not infer commitments.",
    auditCriteria: ["Completeness", "Ownership", "Evidence", "Policy alignment"],
    budgetCategories: ["Revenue", "Payroll", "Marketing", "Operations", "Software"],
    reportingCurrency: "",
    reportingYear: String(new Date().getFullYear()),
    responseStyle: "Clear, concise and professional",
  },
  {
    id: "acme-corp",
    name: "Acme Corp",
    industry: "B2B services",
    businessType: "Professional services",
    context: "Demo company profile for commercial customer conversations.",
    description: "B2B services profile for customer communication and business review.",
    departments: ["Executive", "Sales", "Operations", "Finance"],
    productsOrServices: ["Managed operations", "Customer implementation"],
    supportTone: "Commercially aware",
    communicationStyle: "Direct and executive-ready",
    riskTolerance: "Medium",
    priorityRules: ["Escalate contract, payment, legal and renewal blockers."],
    escalationRoles: ["Sales Lead", "Finance Team", "Operations Lead"],
    auditCriteria: ["Contract evidence", "Approval trail", "Service delivery risk"],
    budgetCategories: ["Revenue", "Client delivery", "Vendors", "Travel"],
    reportingCurrency: "USD",
    responseStyle: "Helpful, direct and commercially aware",
  },
  {
    id: "demo-saas",
    name: "SaaS Company",
    industry: "Software as a service",
    businessType: "B2B SaaS",
    context: "Demo SaaS profile for product questions, trials and account issues.",
    description: "Software company profile for trials, renewals, onboarding and support workflows.",
    departments: ["Executive", "Sales", "Customer Support", "Engineering", "Security"],
    productsOrServices: ["Subscription platform", "API access", "Onboarding"],
    supportTone: "Action-oriented",
    communicationStyle: "Product-informed and concise",
    riskTolerance: "Low",
    priorityRules: ["Escalate security incidents, billing failures and enterprise blockers."],
    escalationRoles: ["Customer Support Manager", "Security Lead", "Engineering Lead"],
    auditCriteria: ["Security review", "SLA impact", "Customer evidence"],
    budgetCategories: ["Revenue", "Cloud hosting", "Support", "Sales", "Engineering"],
    reportingCurrency: "USD",
    responseStyle: "Product-informed and action-oriented",
  },
  {
    id: "support-center",
    name: "Support Center",
    industry: "Customer operations",
    businessType: "Customer support",
    context: "Demo support profile for service requests, complaints and urgent issues.",
    description: "Support operations profile for complaint, escalation and service-quality review.",
    departments: ["Customer Support", "Operations", "Compliance"],
    productsOrServices: ["Support desk", "Customer service"],
    supportTone: "Empathetic",
    communicationStyle: "Structured and escalation-aware",
    riskTolerance: "Low",
    priorityRules: ["Escalate complaints, access issues, payment impact and legal threats."],
    escalationRoles: ["Customer Support Manager", "Operations Lead"],
    auditCriteria: ["Response timeliness", "Escalation handling", "Resolution evidence"],
    budgetCategories: ["Payroll", "Software", "Training", "Customer credits"],
    reportingCurrency: "USD",
    responseStyle: "Empathetic, structured and escalation-aware",
  },
  {
    id: "ecommerce-business",
    name: "E-commerce Business",
    industry: "Retail",
    businessType: "Online commerce",
    context: "Profile for order questions, refunds, product inquiries and marketplace operations.",
    description: "E-commerce profile for sales, support, fulfillment and customer experience review.",
    departments: ["Customer Support", "Sales", "Operations", "Marketing", "Finance"],
    productsOrServices: ["Online products", "Order fulfillment", "Returns"],
    supportTone: "Helpful and concise",
    communicationStyle: "Customer-first",
    riskTolerance: "Medium",
    priorityRules: ["Escalate refund disputes, payment issues and fulfillment delays."],
    escalationRoles: ["Customer Support Manager", "Operations Lead"],
    auditCriteria: ["Order evidence", "Refund policy alignment", "Customer impact"],
    budgetCategories: ["Revenue", "Inventory", "Shipping", "Marketing", "Refunds"],
    reportingCurrency: "USD",
    responseStyle: "Helpful, concise and customer-first",
  },
  {
    id: "professional-services",
    name: "Professional Services",
    industry: "Consulting",
    businessType: "Client services",
    context: "Profile for client communication, scope, invoices and delivery risk.",
    description: "Professional services profile for project updates, client escalations and audit-ready records.",
    departments: ["Executive", "Operations", "Finance", "Sales"],
    productsOrServices: ["Consulting", "Implementation", "Advisory"],
    supportTone: "Measured and professional",
    communicationStyle: "Executive-ready",
    riskTolerance: "Low",
    priorityRules: ["Escalate scope changes, unpaid invoices and legal concerns."],
    escalationRoles: ["Operations Lead", "Finance Team"],
    auditCriteria: ["Scope evidence", "Approval trail", "Invoice support"],
    budgetCategories: ["Revenue", "Contractors", "Travel", "Software"],
    reportingCurrency: "USD",
    responseStyle: "Measured, professional and evidence-aware",
  },
  {
    id: "nonprofit-organization",
    name: "Nonprofit Organization",
    industry: "Nonprofit",
    businessType: "Mission-driven organization",
    context: "Profile for donor communication, program operations and grant reporting.",
    description: "Nonprofit profile for operations, donor support and responsible budget review.",
    departments: ["Executive", "Finance", "Operations", "Marketing"],
    productsOrServices: ["Programs", "Donor services", "Community support"],
    supportTone: "Respectful and mission-aware",
    communicationStyle: "Clear and accountable",
    riskTolerance: "Low",
    priorityRules: ["Escalate restricted-fund, grant, donor and compliance concerns."],
    escalationRoles: ["Executive", "Finance Team"],
    auditCriteria: ["Grant evidence", "Restricted-fund handling", "Program documentation"],
    budgetCategories: ["Donations", "Grants", "Programs", "Fundraising", "Administration"],
    reportingCurrency: "USD",
    responseStyle: "Respectful, accountable and mission-aware",
  },
  {
    id: "small-business",
    name: "Small Business",
    industry: "Small business",
    businessType: "Owner-operated business",
    context: "Profile for owner-led communications, basic budget review and operational follow-up.",
    description: "Small business profile for practical communication, budget and process review.",
    departments: ["Executive", "Finance", "Operations", "Sales"],
    productsOrServices: ["Local services", "Customer support"],
    supportTone: "Plainspoken and practical",
    communicationStyle: "Concise and action-focused",
    riskTolerance: "Medium",
    priorityRules: ["Escalate cash-flow, legal, customer-impact and vendor issues."],
    escalationRoles: ["Business Owner", "Finance Team"],
    auditCriteria: ["Receipts", "Approval notes", "Customer impact", "Owner review"],
    budgetCategories: ["Revenue", "Rent", "Payroll", "Marketing", "Supplies"],
    reportingCurrency: "USD",
    responseStyle: "Plainspoken, practical and action-focused",
  },
];

export function getBusinessProfile(profileId: string) {
  return (
    businessProfiles.find((profile) => profile.id === profileId) ??
    businessProfiles[0]
  );
}
